[workspace]
authors = ["Allen Guo <allenguo@vastaitech.com>"]
channels = ["conda-forge"]
name = "pixi-env"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
build = "bash scripts/build.sh"
extract = "bash scripts/extract.sh"

[dependencies]
rattler-build = ">=0.72.2,<0.73"
micromamba = ">=2.9.0,<3"
patchelf = ">=0.19.1,<0.20"
